### PR TITLE
fixed SEO issue

### PR DESCRIPTION
**Pull request by bsaikiran618**

### CODE REVIEW

**Comment by sanath1599** [comment]
@bsaikiran618 This doesn't seem to address cssoc/cc.html,cssoc/gallery.html title change and meta update? please confirm if i am wrong

**Comment by sanath1599** [comment]
@bsaikiran618 @Saravanan-Jodavula please rename cc to codecraft.html and cssoc.html, these pages will get indexed in google and if you change it later will cause 404 errors resulting in downgrade of the rank in future. so better to change it now itself

**Comment by bsaikiran618** [comment]
> @bsaikiran618 This doesn't seem to address cssoc/cc.html,cssoc/gallery.html title change and meta update? please confirm if i am wrong

The description is now 149 characters

**Comment by bsaikiran618** [comment]
changed cc.html files' name

**Comment by sanath1599** [comment]
good job @bsaikiran618 & @Saravanan-Jodavula Merging the request!

**Comment by bsaikiran618** [comment]
Thenks.

**Pull request merged**
