### PR TITLE
Added a home button to navigate back to editorial landing

### PR DESCRIPTION
**Pull request by akshayrajp**

### CODE REVIEW

**Comment by akshayrajp** [comment]
@sanath1599 this PR addresses the issue of not being able to navigate back from the editorial to the main website. A home button has been added by @Aaris03Khan , which will redirect the user back to the Editorial landing page.

**Comment by akshayrajp** [comment]
> Can you add text beside the home button? something short like back to home something, it wasn't very evident that the button would take me back home on first sight!

Alright, on it.

**Comment by sanath1599** [comment]
> > Can you add text beside the home button? something short like back to home something, it wasn't very evident that the button would take me back home on first sight!
> 
> Alright, on it.

Once done, go ahead and merge request, everything else is fine. This also seems to address #103 so I've attached and once this pull request is merged feel free to close #103

**Comment by sanath1599** [comment]
image
@Aaris03Khan @akshayrajp 
Please create an index.html file that redirects to the first problem. Click on cc beta is resulting in 404 error

**Comment by sanath1599** [comment]
> image
> @Aaris03Khan @akshayrajp
> Please create an index.html file that redirects to the first problem. Click on cc beta is resulting in 404 error

Same applies for codeCraft, always remember to have an index file for every directory in the future!

**Comment by akshayrajp** [comment]
This issue has already been fixed in the PR placed by @Aaris03Khan . Please do check it in the deploy preview

As for the index.html file, noted.

**Comment by sanath1599** [comment]
> This 404 issue has already been fixed in the PR placed by @Aaris03Khan . Please do check it in the deploy preview
> 
> As for the index.html file, noted.

Cool then, my bad didn't realize I was on the deployed build and not on the preview! Good work!

**Comment by akshayrajp** [comment]
@akylus the issue https://github.com/coding-Studio-vbit/cswebsite/issues/49 has been fixed here.

**Pull request merged**
