### PR TITLE
Fixes for issue #89

### PR DESCRIPTION
**Pull request by akshayrajp**
- Added navbar for achievements page
- Fixed the font size and the font itself.

### CODE REVIEW

**Comment by akshayrajp** [comment]
@akylus This fixes issue #89 . 
Please check.

**Comment by akshayrajp** [comment]
Note that the favicons will appear once after the PR is merged because the WhiteLogo.png has to get added to the master branch, which will happen after the PR is merged.

**Comment by akylus** [comment]
image

Main page has messed up due to merge conflict

**Comment by akylus** [comment]
image

**Comment by akshayrajp** [comment]
Alright, imma fix them

**Comment by akylus** [comment]
Great job!

**Comment by akshayrajp** [comment]
Over and out

**Pull request merged**
